[tool.pyright]
include = ["src", "test"]
exclude = [
    "**/__pycache__",
    "src/typestubs"
]
ignore = []
defineConstant = {}
stubPath = "src/stubs"
venv = ".venv"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.10"
pythonPlatform = "Linux"

executionEnvironments = []

[tool.ruff]
line-length = 80

select = [
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "I",  # isort
    "N",  # PEP8 naming
    "D",  # pydocstyle
]

ignore = ["D203", "D212"]

[tool.autopep8]
max_line_length = 80
aggressive = 3
experimental = true
